import type { Conversation, Listing, User } from "./types";
import { CAMPUS } from "./constants";

export const CURRENT_USER_ID = "u-janeshwar";

export const users: User[] = [
  {
    id: "u-janeshwar",
    name: "Janeshwar",
    course: "B.Tech Computer Science",
    year: "1st year",
    campus: CAMPUS,
    hostel: "Adhiyaman Hostel",
    rating: 4.8,
    reviews: 14,
    bio: "CSE Fresher who keeps a drafter, a half-charged power bank, and too many PDFs. Happy to lend calculators before mid-sems.",
    skills: ["Python", "Linux", "Cyber Security"],
    exchangesCompleted: 7,
    avatarHue: 152,
    initials: "JN",
  },
  {
    id: "u-aanya",
    name: "Aanya Sharma",
    course: "B.Tech Electronics",
    year: "3rd year",
    campus: CAMPUS,
    hostel: "M-Block Hostel",
    rating: 4.9,
    reviews: 31,
    bio: "Labs until 9pm. Selling gear I outgrew, tutoring first-years who fear circuits.",
    skills: ["Digital electronics", "MATLAB"],
    exchangesCompleted: 19,
    avatarHue: 18,
    initials: "AS",
  },
  {
    id: "u-rohan",
    name: "Rohan Mehta",
    course: "B.Tech Mechanical",
    year: "2nd year",
    campus: CAMPUS,
    hostel: "Kaari Hostel",
    rating: 4.6,
    reviews: 9,
    bio: "Cycle club + workshop junkie. Fair trades only, hostel pickup after 6.",
    skills: ["Bike repair"],
    exchangesCompleted: 5,
    avatarHue: 210,
    initials: "RM",
  },
  {
    id: "u-priya",
    name: "Priya Nair",
    course: "B.Des Interaction Design",
    year: "4th year",
    campus: CAMPUS,
    hostel: "Meenakshi Hostel",
    rating: 5,
    reviews: 22,
    bio: "Portfolio reviews, poster gigs, and a cupboard of event merch I will never wear again.",
    skills: ["Poster design", "Portfolio reviews"],
    exchangesCompleted: 16,
    avatarHue: 280,
    initials: "PN",
  },
  {
    id: "u-atharva",
    name: "Atharva Vadhneri",
    course: "B.Tech Computer Science",
    year: "3rd year",
    campus: CAMPUS,
    hostel: "M-Block Hostel",
    rating: 4.7,
    reviews: 18,
    bio: "Python TA. Runs the Sunday coding circle in LH-3 when the AC works.",
    skills: ["Python", "Web dev", "Interview prep"],
    exchangesCompleted: 24,
    avatarHue: 195,
    initials: "DP",
  },
  {
    id: "u-meera",
    name: "Meera Iyer",
    course: "B.Tech Biotechnology",
    year: "1st year",
    campus: CAMPUS,
    hostel: "Meenakshi Hostel",
    rating: 4.5,
    reviews: 4,
    bio: "Lab coat collector (accidentally). Notes are colour-coded; please return the highlighters.",
    skills: ["Bio notes"],
    exchangesCompleted: 2,
    avatarHue: 42,
    initials: "MI",
  },
  {
    id: "u-ishaan",
    name: "Ishaan Kapoor",
    course: "B.Tech Civil",
    year: "3rd year",
    campus: CAMPUS,
    hostel: "Off-campus",
    rating: 4.4,
    reviews: 11,
    bio: "Off-campus but on campus 9 to 6. Drafter, lab coat, and a very patient scientific calculator.",
    skills: [],
    exchangesCompleted: 8,
    avatarHue: 95,
    initials: "IK",
  },
  {
    id: "u-sara",
    name: "Sara Qureshi",
    course: "MBA",
    year: "1st year",
    campus: CAMPUS,
    hostel: "Faculty / Staff quarters",
    rating: 4.8,
    reviews: 7,
    bio: "Cultural fest tickets, case-comp leftovers, and a charger that actually stays in the bag.",
    skills: ["Public speaking"],
    exchangesCompleted: 6,
    avatarHue: 330,
    initials: "SQ",
  },
];

const img = (id: string, extra = "") =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=80${extra}`;

export const listings: Listing[] = [
  {
    id: "l-maths",
    title: "Engineering Mathematics — Grewal, 44th ed.",
    description:
      "Highlighted through Unit 4, no torn pages. Perfect if you are heading into mid-sems and the library copies are already claimed. Pickup from Ganga after 7pm or Sunday noon.",
    category: "Books",
    exchangeType: "sell",
    price: 280,
    condition: "Good",
    location: "Main campus · Ganga Hostel",
    hostel: "Ganga Hostel",
    availability: "Weeknights after 7 · Sundays",
    images: [img("photo-1544716278-ca5e3f4abd8c"), img("photo-1512820790803-83ca734da794")],
    preferredExchange: "UPI or swap for a clean Physics 2 textbook",
    ownerId: "u-janeshwar",
    createdAt: "2026-08-22T09:10:00.000Z",
    featured: true,
    views: 148,
    savedCount: 23,
    status: "active",
  },
  {
    id: "l-calc",
    title: "Casio fx-991EX ClassWiz — 2-day lend",
    description:
      "Scientific calculator, original case, solar still works. I need it back before Thursday lab. Ideal for numericals you forgot to borrow from the department.",
    category: "Electronics",
    exchangeType: "lend",
    price: 40,
    priceNote: "/ day",
    condition: "Like new",
    location: "Academic block · LH-2",
    hostel: "Yamuna Hostel",
    availability: "Today–Wednesday",
    images: [img("photo-1587145820266-a5951ee6f620"), img("photo-1611224923853-80b023f02d71")],
    preferredExchange: "Hostel ID as a courtesy hold",
    ownerId: "u-aanya",
    createdAt: "2026-08-24T14:40:00.000Z",
    featured: true,
    views: 312,
    savedCount: 61,
    status: "active",
  },
  {
    id: "l-charger",
    title: "65W USB-C laptop charger (Dell/HP/Lenovo)",
    description:
      "GaN brick + 2m cable. Saved me through three mid-sems. Selling because I switched to a 100W. Tested this morning on a Yoga and a Mac dongle.",
    category: "Electronics",
    exchangeType: "sell",
    price: 750,
    condition: "Good",
    location: "Narmada Hostel lobby",
    hostel: "Narmada Hostel",
    availability: "Evenings 6–9",
    images: [img("photo-1583863788434-e58a36330cf0"), img("photo-1484704849700-f032a568e944")],
    preferredExchange: "Cash/UPI · no courier",
    ownerId: "u-rohan",
    createdAt: "2026-08-21T11:00:00.000Z",
    views: 90,
    savedCount: 12,
    status: "active",
  },
  {
    id: "l-ticket",
    title: "SRM Cultural Night — 1 standing ticket",
    description:
      "Can't make Saturday (family function). Row-free standing, includes a drink coupon they probably won't honour after 9. Transfer on the fest portal in 2 minutes.",
    category: "Tickets",
    exchangeType: "sell",
    price: 350,
    condition: "Digital",
    location: "Campus · transfer online",
    hostel: "Faculty / Staff quarters",
    availability: "Until Friday 8pm",
    images: [img("photo-1540039155733-5bb30b53aa14"), img("photo-1501281668745-f2f7751f873e")],
    preferredExchange: "UPI then instant transfer",
    ownerId: "u-sara",
    createdAt: "2026-08-23T18:05:00.000Z",
    featured: true,
    views: 421,
    savedCount: 44,
    status: "active",
  },
  {
    id: "l-python",
    title: "Python tutoring — 1:1, first-year friendly",
    description:
      "Loops to pandas. I TA CS101. We can sit in the library quiet wing or a Google Meet if you are off-campus. Bring the assignment, not just 'please explain coding'.",
    category: "Skills",
    exchangeType: "skill",
    price: 250,
    priceNote: "/ session",
    condition: "Digital",
    location: "Central library or online",
    hostel: "Ganga Hostel",
    availability: "Sun 10–1 · Tue/Thu 8–9pm",
    images: [img("photo-1522202176988-66273c2fd55f"), img("photo-1515879218367-8466d910aaa4")],
    preferredExchange: "₹250/hr or a decent coffee + notes swap",
    ownerId: "u-dev",
    createdAt: "2026-08-20T08:30:00.000Z",
    featured: true,
    views: 267,
    savedCount: 38,
    status: "active",
  },
  {
    id: "l-notes",
    title: "Semester 3 CSE notes — OS, DBMS, DAA",
    description:
      "Handwritten + typed mix. Topped DBMS last term; OS is messy but complete. Google Drive folder, no watermark spam. Free if you add one diagram I missed.",
    category: "Study Material",
    exchangeType: "giveaway",
    price: 0,
    condition: "Digital",
    location: "Drive link after chat",
    hostel: "Ganga Hostel",
    availability: "Anytime",
    images: [img("photo-1456513080800-7d93acd79315"), img("photo-1434030216411-0b793f4b4173")],
    preferredExchange: "Free · please don't resell the pack",
    ownerId: "u-janeshwar",
    createdAt: "2026-08-19T16:20:00.000Z",
    views: 198,
    savedCount: 72,
    status: "active",
  },
  {
    id: "l-headphones",
    title: "Sony WH-CH720N — campus commute pair",
    description:
      "ANC still decent, earcups a bit shiny. Comes with original cable. Great for the 7:40 Pune shuttle. Looking to sell before fest week.",
    category: "Electronics",
    exchangeType: "sell",
    price: 2200,
    condition: "Good",
    location: "Krishna Hostel",
    hostel: "Krishna Hostel",
    availability: "Weekdays lunch",
    images: [img("photo-1505740420928-5e560c06d30e"), img("photo-1484704849700-f032a568e944")],
    preferredExchange: "UPI · can demo in mess",
    ownerId: "u-priya",
    createdAt: "2026-08-18T12:00:00.000Z",
    views: 76,
    savedCount: 9,
    status: "active",
  },
  {
    id: "l-cycle",
    title: "Hero Sprint 26\" — hostel-to-gate bicycle",
    description:
      "Gears click once but it climbs the back gate fine. Lock included. I am moving off-campus and the society has no cycle stand. Helmet not included (lost).",
    category: "Other",
    exchangeType: "trade",
    price: 1800,
    condition: "Fair",
    location: "Narmada cycle stand",
    hostel: "Narmada Hostel",
    availability: "Sat–Sun mornings",
    images: [img("photo-1502744688674-c619d1586c9e"), img("photo-1507035895480-2b3156c31fc8")],
    preferredExchange: "Trade for a monitor or sell at ₹1,800",
    ownerId: "u-rohan",
    createdAt: "2026-08-17T07:45:00.000Z",
    featured: true,
    views: 133,
    savedCount: 17,
    status: "active",
  },
  {
    id: "l-labcoat",
    title: "Lab coat — size M, washed after chem lab",
    description:
      "White, one blue pen stain near the pocket. Bio and chem first-years, this will pass attendance. Lend for the week or keep if you stitch the stain.",
    category: "Study Material",
    exchangeType: "lend",
    price: 0,
    condition: "Good",
    location: "Yamuna Hostel · Block C",
    hostel: "Yamuna Hostel",
    availability: "Tonight onwards",
    images: [img("photo-1582719471384-894fbb16e074"), img("photo-1579684385127-1ef15d508118")],
    preferredExchange: "Free lend · return by next Friday",
    ownerId: "u-meera",
    createdAt: "2026-08-24T06:15:00.000Z",
    views: 54,
    savedCount: 8,
    status: "active",
  },
  {
    id: "l-workshop",
    title: "Sunday coding workshop — 8 seats left",
    description:
      "Build a tiny campus app in 3 hours. HTML/CSS/JS, no prior required. Hosted by the CSE club in LH-3. Bring a laptop that actually charges.",
    category: "Other",
    exchangeType: "giveaway",
    price: 0,
    condition: "Digital",
    location: "LH-3, Academic block",
    hostel: "Ganga Hostel",
    availability: "This Sunday 10am–1pm",
    images: [img("photo-1516321318423-f06f85e504b3"), img("photo-1531482615713-2afd69097998")],
    preferredExchange: "Free · RSVP in chat",
    ownerId: "u-dev",
    createdAt: "2026-08-24T10:00:00.000Z",
    featured: true,
    views: 389,
    savedCount: 91,
    status: "active",
  },
  {
    id: "l-mattress",
    title: "Extra hostel mattress + clean cover",
    description:
      "Guests during convocation? This 4-inch foam mattress lived one semester. Cover washed yesterday. Pickup from Yamuna — too bulky to walk across campus.",
    category: "Hostel",
    exchangeType: "giveaway",
    price: 0,
    condition: "Fair",
    location: "Yamuna Hostel · 214",
    hostel: "Yamuna Hostel",
    availability: "This weekend only",
    images: [img("photo-1505693416388-ac5ce068fe85"), img("photo-1555041469-a586c61ea9bc")],
    preferredExchange: "Free · you carry it",
    ownerId: "u-aanya",
    createdAt: "2026-08-22T19:30:00.000Z",
    views: 41,
    savedCount: 5,
    status: "active",
  },
  {
    id: "l-drafter",
    title: "Mini drafter + engineering graphics kit",
    description:
      "Used for one EG course. Scales still readable. Giving away because civil friends already have three. First-year mechanicals, please take this.",
    category: "Free Stuff",
    exchangeType: "giveaway",
    price: 0,
    condition: "Good",
    location: "Off-campus cafe near gate 2",
    hostel: "Off-campus",
    availability: "Weekdays 5:30pm",
    images: [img("photo-1503387762-592deb58ef4e"), img("photo-1452860606245-08befc0ff44b")],
    preferredExchange: "Free",
    ownerId: "u-ishaan",
    createdAt: "2026-08-16T13:10:00.000Z",
    views: 63,
    savedCount: 11,
    status: "active",
  },
  {
    id: "l-arduino",
    title: "Arduino Uno starter kit — trade for a Raspberry Pi",
    description:
      "Uno R3, jumper wires, sensors, that one servo everyone loses. Looking to trade for a Pi Zero or sell if the offer is not embarrassing.",
    category: "Electronics",
    exchangeType: "trade",
    price: 900,
    condition: "Like new",
    location: "ECE lab corridor",
    hostel: "Yamuna Hostel",
    availability: "After 4pm labs",
    images: [img("photo-1555664424-4e7905cdb66c"), img("photo-1518770660439-4636190af475")],
    preferredExchange: "Trade Pi Zero / sell ₹900",
    ownerId: "u-aanya",
    createdAt: "2026-08-15T09:00:00.000Z",
    views: 88,
    savedCount: 14,
    status: "active",
  },
  {
    id: "l-posters",
    title: "Fest posters + Instagram creatives",
    description:
      "Need a club poster that does not look like Comic Sans and clipart? I design for Cultural and E-Cell. 48-hour turnaround if you send copy on time.",
    category: "Services",
    exchangeType: "skill",
    price: 400,
    priceNote: "/ poster",
    condition: "Digital",
    location: "Online / Krishna common room",
    hostel: "Krishna Hostel",
    availability: "This week, 3 slots",
    images: [img("photo-1561070791-2526d30994b5"), img("photo-1626785774573-4b799315345d")],
    preferredExchange: "₹400 or a campus merch trade",
    ownerId: "u-priya",
    createdAt: "2026-08-21T21:12:00.000Z",
    views: 112,
    savedCount: 20,
    status: "active",
  },
  {
    id: "l-kettle",
    title: "1.2L electric kettle — hostel legal",
    description:
      "Maggi at 1am without tripping the floor MCB. Coil is clean. Selling because my roommate brought a better one and the cupboard is full.",
    category: "Hostel",
    exchangeType: "sell",
    price: 450,
    condition: "Good",
    location: "Ganga Hostel · 118",
    hostel: "Ganga Hostel",
    availability: "Tonight",
    images: [img("photo-1564890365470-2dc4b32a3be3"), img("photo-1571934811356-5cc061b6821f")],
    preferredExchange: "UPI",
    ownerId: "u-janeshwar",
    createdAt: "2026-08-23T22:00:00.000Z",
    views: 37,
    savedCount: 4,
    status: "active",
  },
  {
    id: "l-gate",
    title: "GATE CS short notes — 2025 attempt",
    description:
      "Condensed OS, CN, DBMS. Not a coaching dump — my own rewrite. Free for anyone sitting GATE this year. Please don't put it behind a Telegram paywall.",
    category: "Study Material",
    exchangeType: "giveaway",
    price: 0,
    condition: "Digital",
    location: "Drive link",
    hostel: "Ganga Hostel",
    availability: "Anytime",
    images: [img("photo-1434030216411-0b793f4b4173"), img("photo-1456513080800-7d93acd79315")],
    preferredExchange: "Free",
    ownerId: "u-dev",
    createdAt: "2026-08-14T15:40:00.000Z",
    views: 244,
    savedCount: 80,
    status: "active",
  },
  {
    id: "l-speak",
    title: "Public speaking clinic — 45 minutes",
    description:
      "If your seminar voice disappears at slide 2, we'll run through it once. MBA first-year. Library discussion rooms or a quiet courtyard.",
    category: "Skills",
    exchangeType: "skill",
    price: 0,
    condition: "Digital",
    location: "Central library discussion rooms",
    hostel: "Faculty / Staff quarters",
    availability: "Wed evenings",
    images: [img("photo-1475721027785-f74eccf877e2"), img("photo-1551836022-d5d88e9218df")],
    preferredExchange: "Free for SRM students",
    ownerId: "u-sara",
    createdAt: "2026-08-20T17:25:00.000Z",
    views: 71,
    savedCount: 13,
    status: "active",
  },
  {
    id: "l-helmet",
    title: "ISI helmet — scooter pillion spare",
    description:
      "Matte black, size L. I keep two; this one can live with a first-year who currently wears a hoodie and optimism.",
    category: "Free Stuff",
    exchangeType: "giveaway",
    price: 0,
    condition: "Good",
    location: "Gate 2 parking",
    hostel: "Off-campus",
    availability: "Tomorrow 6pm",
    images: [img("photo-1558980664-769d59546b3d"), img("photo-1558618666-fcd25c85cd64")],
    preferredExchange: "Free",
    ownerId: "u-ishaan",
    createdAt: "2026-08-25T03:10:00.000Z",
    views: 19,
    savedCount: 3,
    status: "active",
  },
];

export const conversations: Conversation[] = [
  {
    id: "c-calc",
    listingId: "l-calc",
    participantIds: ["u-janeshwar", "u-aanya"],
    status: "negotiating",
    lastAt: "2026-08-25T02:40:00.000Z",
    messages: [
      {
        id: "m1",
        fromId: "u-janeshwar",
        text: "Hey Aanya — need the ClassWiz for Wednesday numericals. Can I pick up tonight from Yamuna?",
        at: "2026-08-24T16:10:00.000Z",
      },
      {
        id: "m2",
        fromId: "u-aanya",
        text: "Yes. ₹40/day is fine. Bring your ID, I'll be in the lobby at 8:15.",
        at: "2026-08-24T16:22:00.000Z",
      },
      {
        id: "m3",
        fromId: "u-janeshwar",
        text: "Perfect. I'll return it Thursday morning before your lab.",
        at: "2026-08-25T02:40:00.000Z",
      },
    ],
  },
  {
    id: "c-python",
    listingId: "l-python",
    participantIds: ["u-janeshwar", "u-dev"],
    status: "new",
    lastAt: "2026-08-25T01:05:00.000Z",
    messages: [
      {
        id: "m4",
        fromId: "u-janeshwar",
        text: "I want someone to teach me Python — specifically file handling + a tiny pandas assignment. Sunday morning still open?",
        at: "2026-08-25T01:05:00.000Z",
      },
    ],
  },
  {
    id: "c-ticket",
    listingId: "l-ticket",
    participantIds: ["u-priya", "u-sara"],
    status: "accepted",
    lastAt: "2026-08-24T20:18:00.000Z",
    messages: [
      {
        id: "m5",
        fromId: "u-priya",
        text: "Still have the standing ticket? I can UPI right now.",
        at: "2026-08-24T19:50:00.000Z",
      },
      {
        id: "m6",
        fromId: "u-sara",
        text: "It's yours. Sending the fest portal transfer. Pay ₹350 to the UPI on my profile.",
        at: "2026-08-24T20:02:00.000Z",
      },
      {
        id: "m7",
        fromId: "u-priya",
        text: "Paid. See you in the crush near the stage.",
        at: "2026-08-24T20:18:00.000Z",
      },
    ],
  },
  {
    id: "c-notes",
    listingId: "l-notes",
    participantIds: ["u-meera", "u-janeshwar"],
    status: "completed",
    lastAt: "2026-08-21T11:00:00.000Z",
    messages: [
      {
        id: "m8",
        fromId: "u-meera",
        text: "Could I grab the DBMS notes? First year but the seniors said your pack is gold.",
        at: "2026-08-20T09:12:00.000Z",
      },
      {
        id: "m9",
        fromId: "u-janeshwar",
        text: "Drive link sent. If a diagram is missing, add it and pass it on.",
        at: "2026-08-20T09:40:00.000Z",
      },
      {
        id: "m10",
        fromId: "u-meera",
        text: "Downloaded. Thank you — marked completed from my side.",
        at: "2026-08-21T11:00:00.000Z",
      },
    ],
  },
  {
    id: "c-cycle",
    listingId: "l-cycle",
    participantIds: ["u-ishaan", "u-rohan"],
    status: "negotiating",
    lastAt: "2026-08-23T08:30:00.000Z",
    messages: [
      {
        id: "m11",
        fromId: "u-ishaan",
        text: "Would you take a 24\" monitor + ₹400 instead of a straight sale?",
        at: "2026-08-23T08:11:00.000Z",
      },
      {
        id: "m12",
        fromId: "u-rohan",
        text: "If the monitor is 1080p and not flickering, yes. Can you bring it Sunday?",
        at: "2026-08-23T08:30:00.000Z",
      },
    ],
  },
];

export const impactSeed = {
  itemsReused: 128,
  moneySaved: 14850,
  itemsDonated: 41,
  successfulExchanges: 96,
  studentsHelped: 74,
};
